services:
    app:
        image: users-bot
        container_name: users-bot
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        network_mode: host
        restart: always
        volumes:
            - /etc/ssl/certs/tg:/etc/ssl/certs/tg:ro
