services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        network_mode: host
        volumes:
            - ./prometheus/config:/etc/prometheus
            - ./prometheus/data:/prometheus
        command: ['--config.file=/etc/prometheus/prometheus.yml', '--web.listen-address=:9099']
        restart: unless-stopped

    node_exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        network_mode: host
        pid: host
        volumes:
            - '/:/host:ro,rslave'
        command:
            - '--path.rootfs=/host'
        restart: unless-stopped

    prometheus-wireguard-exporter:
        image: mindflavor/prometheus-wireguard-exporter
        container_name: wgexporter
        network_mode: host
        cap_add:
            - NET_ADMIN
        command: -a true
        restart: unless-stopped
