name: Build and Transfer keys-bot

run-name: 'Build and Transfer keys-bot'

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Target environment'
                required: true
                default: t
                type: choice
                options:
                    - turkey
                    - us
                    - neth
                    - fin

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  touch .env
                  echo "IKE_CLIENTS_DIR=/srv/ikev2/clients" >> .env
                  echo "WG_CLIENTS_DIR=/srv/wireguard/clients" >> .env
                  echo "OVPN_CLIENTS_DIR=/srv/openvpn/clients" >> .env
              working-directory: apps/keys

            - name: Build Docker image
              run: docker compose -f ./docker-compose.yml build --no-cache
              working-directory: apps/keys

            - name: Save Docker image
              run: docker save keys-bot -o keys-bot.tar
              working-directory: apps/keys

            - name: Upload Docker image
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.VPN_SERVER_HOST }}
                  username: ${{ secrets.VPN_SERVER_USERNAME }}
                  key: ${{ secrets.VPN_SERVER_SSH_KEY }}
                  source: ./apps/keys/keys-bot.tar
                  target: ${{ secrets.VPN_SERVER_APP_DIRECTORY }}/apps/keys

            - name: Load and run Docker image
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.VPN_SERVER_HOST }}
                  username: ${{ secrets.VPN_SERVER_USERNAME }}
                  key: ${{ secrets.VPN_SERVER_SSH_KEY }}
                  script: |
                      cd ${{ secrets.VPN_SERVER_APP_DIRECTORY }}/apps/keys
                      docker load -i keys-bot.tar
                      docker compose up -d --no-build app
                      rm keys-bot.tar
