name: Build and Transfer users-bot

run-name: 'Build and Transfer users-bot'

on:
    workflow_dispatch:

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.1
              with:
                  ssh-private-key: ${{ secrets.DB_SERVER_SSH_KEY }}

            - name: Add VPN server to known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.DB_SERVER_HOST }} >> ~/.ssh/known_hosts

            - name: Add sheets-api.json
              working-directory: apps/users
              run: echo '${{ secrets.SHEETS_API }}' > sheets-api.json

            - name: Build Docker image
              working-directory: apps/users
              run: docker compose build --no-cache

            - name: Upload Docker image
              working-directory: apps/users
              run: |
                  docker save users-bot:latest | ssh ${{ secrets.DB_SERVER_USERNAME }}@${{ secrets.DB_SERVER_HOST }} 'docker load'

            - name: Upload docker-compose.yml via SSH
              working-directory: apps/users
              run: |
                  cat docker-compose.yml | ssh ${{ secrets.DB_SERVER_USERNAME }}@${{ secrets.DB_SERVER_HOST }} "cat > ${{ secrets.DB_SERVER_APP_DIRECTORY }}/docker-compose.yml"

            - name: Restart container on server
              run: |
                  ssh ${{ secrets.DB_SERVER_USERNAME }}@${{ secrets.DB_SERVER_HOST }} '
                    cd ${{ secrets.DB_SERVER_APP_DIRECTORY }}
                    docker compose up -d
                  '
