name: Build and Deploy wg-manager

run-name: 'Build and Deploy wg-manager'

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Target environment'
                required: true
                default: t
                type: choice
                options:
                    - turkey
                    - us
                    - neth
                    - fin

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22'

            - name: Build binary
              run: |
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .
              working-directory: apps/infrastructure/wireguard

            - name: Archive service
              run: tar -czf service.tar.gz wgmanager wgmanager.service
              working-directory: apps/infrastructure/wireguard

            - name: Upload to server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.VPN_SERVER_HOST }}
                  username: ${{ secrets.VPN_SERVER_USERNAME }}
                  key: ${{ secrets.VPN_SERVER_SSH_KEY }}
                  source: ./apps/infrastructure/wireguard/service.tar.gz
                  target: ${{ secrets.WG_SERVICE_DIRECTORY }}

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.VPN_SERVER_HOST }}
                  username: ${{ secrets.VPN_SERVER_USERNAME }}
                  key: ${{ secrets.VPN_SERVER_SSH_KEY }}
                  script: |
                      cd ${{ secrets.WG_SERVICE_DIRECTORY }}
                      tar -xzf service.tar.gz
                      rm service.tar.gz
                      sudo mv wgmanager /usr/local/bin
                      sudo systemctl daemon-reload
                      sudo systemctl restart wgmanager.service
